[package]
name = "display_sensor_data"
version = "0.1.0"
authors = ["sambenko <sam.benko@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hal = { package = "esp32s3-hal", version = "0.8.0" }
esp-backtrace = { version = "0.6.0", features = ["esp32s3", "panic-handler", "print-uart"] }
esp-println       = { version = "0.4.0", features = ["esp32s3"] }
