[package]
name = "display_sensor_data"
version = "0.1.0"
authors = ["sambenko <sam.benko@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp32s3-hal = "0.9.0"
esp-wifi = { git = "https://github.com/esp-rs/esp-wifi.git", features = ["big-heap", "phy-enable-usb", "esp32s3", "embedded-svc", "wifi"] }
smoltcp = { version = "0.9.1", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
esp-backtrace = { git = "https://github.com/esp-rs/esp-backtrace", version = "0.7.0", features = ["esp32s3", "panic-handler", "print-uart"] }
esp-println = { version = "0.5.0", features = ["esp32s3"] }

embedded-hal = "0.2.3"
embedded-svc = { version = "0.25.0", default-features = false }
embedded-io = "0.4.0"
display-interface-spi = "0.4"
embedded-graphics = "0.8.0"
mipidsi = "0.7.1"
ui = { path = "./ui"}

esp-mbedtls = { git = "https://github.com/esp-rs/esp-mbedtls.git" }
bme680 = "0.6.0"

[features]
default = [ "esp32s3-hal/eh1" ]
